version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: sportclubs-postgres-dev
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - sportclubs-network-dev
    restart: always

  redis:
    image: redis:7.4.2-bookworm
    container_name: sportclubs-redis-dev
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data-dev:/data
    networks:
      - sportclubs-network-dev
    restart: always

networks:
  sportclubs-network-dev:
    driver: bridge

volumes:
  postgres-data-dev:
  redis-data-dev: